### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by mplacona** [jlamendo/ha-sensor.owlet#19]
Hey folks, just got an Owlet V3 (replacing a V2) and installed this via HACS.

I've added the following with my own credentials to my configuration.yaml and restarted. Yet I can't see anything show up in HA. 

```
sensor:
  - platform: owlet
    username: "owlet_api_email"
    password: !secret owlet_password
    region: "europe"
```

Only thing I did different from what's on the readme is use "Europe" instead of "world".

I'm sure I'm probably missing something. I had this running before with [this repository](https://github.com/CAB426/HomeAssistant-Owlet), so I know my credentials are correct.

Thanks
